spring.application.name=mundial-api

server.port=8105

# ---- Conexion a MongoDB Atlas ----
spring.data.mongodb.uri=mongodb+srv://joelitodedavid_db_user:uts2026*@pcjoel.6jsqksy.mongodb.net/db
spring.data.mongodb.database=db

# ---- Thymeleaf ----
spring.thymeleaf.cache=false
